language: java
jdk:
- oraclejdk8
deploy:
  provider: openshift
  user: login-openshift
  password: password-openshift
  app: mytomcatapp
  domain: dquintanilha
  on:
    repo: douglasquintanilha/geradordeprovas
