install: /bin/true
script: /bin/true # Isso serve para ele dar skips nos testes que Maven faz no travis
jdk:
- oraclejdk7
language: java # Não sei por que , mas o Travis parece que precisar dar um commit para que seja detectado alguma mudança e ai sim o deploy vá para o openshift
deploy:  
  provider: openshift
  skip_cleanup: true
  user: dougquintanilha@gmail.com
  password:
    secure: ff9MFLEI6QruoA7PHG2NxIUZnGKUL/edFVceUd1pDXwVV6KcxqCKfg9zF7y/g5csdSqfHXONjac1745Id6b+RKM/I1IYnRFfh4WT6Cb3L7yJa2SNpzb70Zkjkz953xPPOK7GW+oaW4lU5nIJkbL6r6JqJPVHjJ0maVHhjIzE1AqDlUBy0xUgdceE+hrQxKHdzhSwXAETLkSk5iFYG4pbyib+hysSkxj4iCkrbjPv9w2EGnYofAbaz0uos2chaLLEoPQ3criSoR5TPkxRsBqatx32ahikbartOmFgfE7ZuPwdrj9T4KTykxPmHk4Ji4KiLiNyyv8UkiBzFc9h4YHfOpB1lzzrPGRlbRYIqoyVsuQtWJGQH7WIMnR73j7EfPKiQ999SGr4ntdLvwJg2Q02SXJDt8gXkGBBNp8u0FKchSILlQSpL2+x7otcAWx74/03HTffR9u3efRnkJfR/B3yZ1/t2iUZ1ToOAgd+iFqJPmTFngc340sx62cPGkvmIlJ4wGhw39LATG68v0r+/mznKs6UN+lZOCQXJmfas9EiVF7dUOeWIf9HWSJspZ2cMMjSuWJiXhHFjAtRSTBW52gdTiU+v2zQlijIyGa0EuaEB+qbdNJw12r5DFzGR8Bui7fGRMyca+oOJvOMQVXtr7OxiM3rU3MMEK1+JiAmmmoo5WE=
  app:
    development: caelumprovasdev
  domain: dquintanilha
  on:
    repo: douglasquintanilha/geradordeprovas
    branch: development
  deployment_branch: master
after_success: 
  ./deploy.sh